services:
  olesa-app:
    build: .
    container_name: olesa-app
    ports:
      - "8000:8000"
    environment:
      - API_KEY=${API_KEY}
    volumes:
      # La DB se guarda en /app (directorio de trabajo del contenedor)
      - ./data:/app
    restart: unless-stopped