services:
  olesa-app:
    build: .
    container_name: olesa-app
    ports:
      - "8000:8000"
    environment:
      - API_KEY=${API_KEY}
      # Esta ruta DEBE ser absoluta dentro del contenedor
      - DB_PATH=/app/data/passmanager.db
    volumes:
      # Mapea tu carpeta local 'data' a la carpeta interna con permisos
      - ./data:/app/data
    restart: unless-stopped